
export const FETCH_PAGES = 'FETCH_PAGES'
export const FETCH_PAGES_PENDING = 'FETCH_PAGES_PENDING'
export const FETCH_PAGES_FULFILLED = 'FETCH_PAGES_FULFILLED'
export const FETCH_PAGES_REJECTED = 'FETCH_PAGES_REJECTED'

export const ADD_PAGE = 'ADD_PAGE'
export const ADD_PAGE_PENDING = 'ADD_PAGE_PENDING'
export const ADD_PAGE_REJECTED = 'ADD_PAGE_REJECTED'
export const ADD_PAGE_FULFILLED = 'ADD_PAGE_FULFILLED'

export const EDIT_PAGE = 'EDIT_PAGE'
export const EDIT_PAGE_PENDING = 'EDIT_PAGE_PENDING'
export const EDIT_PAGE_FULFILLED = 'EDIT_PAGE_FULFILLED'
export const EDIT_PAGE_REJECTED = 'EDIT_PAGE_REJECTED'

export const REMOVE_PAGE = 'REMOVE_PAGE'
export const REMOVE_PAGE_FULFILLED = 'REMOVE_PAGE_FULFILLED'

export const SET_TEXT_FILTER = 'SET_TEXT_FILTER'
export const SORT_BY_TITLE = 'SORT_BY_TITLE'
export const SORT_BY_DATE = 'SORT_BY_DATE'
export const SORT_BY_ACTIVE = 'SORT_BY_ACTIVE'